[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_type = "semver"
version = "0.4.0"
update_changelog_on_bump = true
major_version_zero = true
annotated_tag = true
bump_message = "chore(release): $current_version → $new_version\n[skip-ci]"

