[hooks]
"before:init" = ["git pull origin main"]
"after:bump" = ["cz changelog --dry-run --start-rev ${latestTag} --unreleased ${version} | cat - CHANGELOG.md | tee ch_body.md && mv ch_body.md CHANGELOG.md"]

[git]
requireBranch = "main"
commitMessage = "chore(release): ${version}"
changelog = "cz changelog --dry-run --start-rev ${latestTag}"
